[ids]
*

[global]
overload_tap_timeout = 300
tapping_term = 100

########################################
# BASE LAYER (MAIN)
########################################

[main]


# layers
space = overloadt(digits, space, 200)

# зміна правого альта з правим контролом (зручність для розкладки graphite)
rightalt = leftcontrol
rightcontrol = rightalt

# Фізична q: швидке натискання = b (графіт), затискання = f_keys
q = overloadt(f_keys, q, 200)

# шар мультимедії
z = overload(multi, z)

# шар навігації
semicolon = overload(arrows, ;)

########################################
# ARROWS
########################################

[arrows]

w = up
a = left
s = down
d = right
q = C-left
e = C-right

j = home
k = end
r = pageup
f = pagedown
u = C-home
i = C-end
f = tab
r = S-tab


########################################
# NUMPAD
########################################

[digits]

u = 7
i = 8
o = 9

j = 4
k = 5
l = 6

m = 1
, = 2
. = 3

n = 0

w = y
e = =
' = +
; = .
p = *
t = grave
/ = S-/

v = enter
z = backspace
b = delete

[ = macro(C-S-left 100ms delete)
] = macro(C-right 100ms C-S-left 100ms delete)
s=[
d=]
x={
c=}
a=(
f=)


########################################
# F KEYS (на тих самих кнопках що numpad)
########################################

[f_keys]

u = f7
i = f8
o = f9

j = f4
k = f5
l = f6

m = f1
, = f2
. = f3

p = f10
[ = f11
] = f12

# швидке вимкнення
` = macro(C-A-f 500ms i 100ms u 100ms u 300ms enter)

########################################
# MULTIMEDIA
########################################
[multi]

u = mute
i = volumedown
o = volumeup
k = playpause
j = previoussong
l = nextsong

# brightnes

[ = brightnessdown
] = brightnessup
